[package]
name = "ta-ko-ho/my-fun-little-repo"
version = "0.2.4"
description = "Astro.dev Wasmer starter package"
readme = "README.md"
repository = "https://github.com/ta-ko-ho/my-fun-little-repo"

[dependencies]
"wasmer/static-web-server" = "*"

[fs]
public = "dist"
